device: '0'
num_workers: 16
weights: ''
num_classes: 51

epoch: 200
warmup: 10  # real epoch = epoch - warmup 
batch_size: 8
nbs: 8

lr: 0.01
lrf: 0.1
optim: 'SGD'
momentum: 0.937

mode: 'test'

weight_decay: 0.0001

frames: 16
img_size: 224
model: vireodev

input_dir: '../../data/hmdb51'
save_dir: '../../outs/3d'

note: '16 fps vireodev auto adapt expand ratio'
